from django.urls import path
from . import views

urlpatterns = [
    path('chats/', views.ChatListCreate.as_view()),
    path('chats/<int:pk>/', views.ChatDetail.as_view()),
    path('chats/<int:pk>/members/', views.ChatMembers.as_view()),
    path('chats/<int:pk>/add-member/', views.AddMember.as_view()),
    path('chats/<int:pk>/remove-member/', views.RemoveMember.as_view()),
    path('chats/<int:pk>/leave/', views.LeaveChat.as_view()),
    path('messages/', views.MessageListCreate.as_view()),
    path('messages/<int:pk>/', views.MessageDetail.as_view()),
    path('media/', views.MediaListCreate.as_view()),
    path('media/<int:pk>/', views.MediaDetail.as_view()),
    path('groups/', views.GroupList.as_view()),
    path('groups/<int:pk>/', views.GroupDetail.as_view()),
    path('channels/', views.ChannelList.as_view()),
    path('channels/<int:pk>/', views.ChannelDetail.as_view()),
    path('channels/<int:pk>/subscribers/', views.ChannelSubscribers.as_view()),
    path('channels/<int:pk>/messages/', views.ChannelMessages.as_view()),
    path('channels/<int:pk>/subscribe/', views.SubscribeChannel.as_view()),
    path('channels/<int:pk>/unsubscribe/', views.UnsubscribeChannel.as_view()),
    path('notifications/', views.NotificationList.as_view()),
    path('notifications/<int:pk>/read/', views.MarkNotificationRead.as_view()),
    path('notifications/read-all/', views.MarkAllNotificationsRead.as_view()),
    path('contacts/', views.ContactListCreate.as_view()),
    path('contacts/<int:pk>/', views.ContactDetail.as_view()),
    path('blocks/', views.BlockListCreate.as_view()),
    path('blocks/<int:pk>/', views.BlockDetail.as_view()),
    path('blocks/unblock/<int:user_id>/', views.UnblockUser.as_view()),
    path('stories/', views.StoryListCreate.as_view()),
    path('stories/mine/', views.MyStories.as_view()),
    path('stories/<int:pk>/', views.StoryDetail.as_view()),
    path('stories/<int:pk>/view/', views.ViewStory.as_view()),
    path('stories/<int:pk>/viewers/', views.StoryViewers.as_view()),
]